### ISSUE TITLE
prune_stat_files not processing INTERP for anom HGT

### ISSUE THREAD

**Issue by malloryprow** [MarcelCaron-NOAA/verif_plotting#1]
In ush/prune_stat_files.py, for plotting anom HGT on line 91 the environment variable 'interp' is called from the environment, but in py_plotting.config the environment variable getting set is 'INTERP', so ush/prune_stat_files.py fails because there is no environment variable called 'interp'.

I did some testing in my clone and changed it to INTERP and everything ran fine.

@MarcelCaron-NOAA I can make my own fork and do a pull request to fix it. I just cloned the code today so not sure if I am missing something here with the issue, so that is why I created this issue.

**Comment by MarcelCaron-NOAA** [comment]
@malloryprow thanks for catching this.  This bug has been hiding in an if statement that only showed up for anom HGT plots, which haven't been tested yet.

There seem to be a couple of instances where "interp" is referenced.. 
 Do you mind putting in a pull request for the changes that worked for you?  I can update the script with those changes.
 
Let me know if you run into any other issues!
